AWSTemplateFormatVersion: "2010-09-09"
Resources:
  DeveloperPolicyNonpCBI0:
    Type: AWS::IAM::ManagedPolicy
    Properties: 
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: '*'
            Resource: '*'
      ManagedPolicyName: DeveloperPolicyNonpCBI0
      Roles: 
        -  DeveloperRoleNonpCBI0
