AWSTemplateFormatVersion: "2010-09-09"
Resources: 
  DeveloperRoleNonpCBI0:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - 
            Effect: "Allow"
            Principal: 
              Service: 
                - "ec2.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
      Description: This role is used by the developer in nonp for the CBI0 appcode operations
      MaxSessionDuration: 3600
      RoleName: DeveloperRoleNonpCBI0
      Tags: 
        - Key: "tier"
          Value: "NonP"
        - Key: "AppCode"
          Value: "CBI0"
        - Key: "App"
          Value: "Certification"